# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.18 is version 38
loaderVersion="[40,)"
# The license for your mod. This is mandatory and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT license"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/MinecraftForge/MinecraftForge/issues"
# If the mods defined in this file should show as separate resource packs
showAsResourcePack=false

[[mods]]
modId="roastedonions"
version="0.2.1"
displayName="roastedonions"
updateJSONURL="https://minecraftforge.net/versions.json"
displayURL="https://minecraftforge.net"
#logoFile="logo.png"
credits="CatStorms Cats: Naldush & Dalli"
authors="Programming by CatStorm, textures & idea by Fyndrix"
description='''
  Top level Danish cuisine
 '''

[[dependencies.roastedonions]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.roastedonions]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"

[[dependencies.roastedonions]]
modId="farmersdelight"
mandatory=true
versionRange="[1.1.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.roastedonions]]
modId="byg"
mandatory=true
versionRange="[1.4,)"
ordering="AFTER"
side="BOTH"